from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


@dataclass(frozen=True)
class TerrainReportInputs:
    dem_path: Path
    slope_path: Path
    hillshade_path: Path
    terrain_risk_path: Path
    qgis_export_path: Path | None = None
    paraview_render_path: Path | None = None
    paraview_state_path: Path | None = None


def path_status(path: Path | None) -> str:
    if path is None:
        return "not provided"
    return "available" if path.exists() else "missing"


def markdown_path_line(label: str, path: Path | None) -> str:
    if path is None:
        return f"- **{label}:** not provided"
    return f"- **{label}:** `{path}` ({path_status(path)})"


def generate_markdown_report(inputs: TerrainReportInputs) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        "# GeoVisLM Terrain Analysis Report",
        "",
        f"Generated: {generated_at}",
        "",
        "## Input Data",
        "",
        markdown_path_line("DEM raster", inputs.dem_path),
        "",
        "## Generated Outputs",
        "",
        markdown_path_line("Slope raster", inputs.slope_path),
        markdown_path_line("Hillshade raster", inputs.hillshade_path),
        markdown_path_line("Terrain risk raster", inputs.terrain_risk_path),
        "",
        "## Terrain Analysis Summary",
        "",
        (
            "The terrain workflow loads a DEM raster, calculates slope in degrees, "
            "generates a hillshade layer, and classifies terrain risk from slope "
            "thresholds."
        ),
        "",
        "Risk classes use the MVP thresholds:",
        "",
        "- Low: 0 to less than 10 degrees",
        "- Medium: 10 to less than 25 degrees",
        "- High: 25 degrees and above",
        "",
        "## Visualization Outputs",
        "",
        markdown_path_line("QGIS export image", inputs.qgis_export_path),
        markdown_path_line("ParaView render image", inputs.paraview_render_path),
        markdown_path_line("ParaView state file", inputs.paraview_state_path),
        "",
        "## Reproducibility Commands",
        "",
        "Generate terrain analysis outputs:",
        "",
        "```bash",
        f"python scripts/run_terrain_analysis.py terrain {inputs.dem_path} --output-dir {inputs.slope_path.parent}",
        "```",
        "",
        "Generate this Markdown report:",
        "",
        "```bash",
        (
            "python scripts/generate_report.py "
            f"--dem {inputs.dem_path} "
            f"--maps-dir {inputs.slope_path.parent} "
            f"--output-md outputs/reports/terrain_analysis.md"
        ),
        "```",
        "",
        "Generate a ParaView terrain render when `pvpython` is available:",
        "",
        "```bash",
        f"pvpython geovis_lm/viz/paraview_terrain.py {inputs.dem_path}",
        "```",
        "",
        "## Limitations and Next Steps",
        "",
        "- Markdown report generation does not require QGIS, ParaView, or GDAL command-line tools.",
        "- PDF export requires the optional `reportlab` Python package.",
        "- Terrain risk thresholds are MVP defaults and should be calibrated for real study areas.",
        "- QGIS and ParaView outputs are referenced when available, but are not generated by this report command.",
        "",
    ]

    return "\n".join(lines)


def write_markdown_report(inputs: TerrainReportInputs, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generate_markdown_report(inputs), encoding="utf-8")
    return output_path


def markdown_to_plain_lines(markdown: str) -> list[str]:
    lines: list[str] = []
    for line in markdown.splitlines():
        cleaned = line.replace("`", "")
        if cleaned.startswith("# "):
            cleaned = cleaned[2:].upper()
        elif cleaned.startswith("## "):
            cleaned = cleaned[3:]
        elif cleaned.startswith("- "):
            cleaned = "- " + cleaned[2:]
        lines.append(cleaned)
    return lines


def write_pdf_report(inputs: TerrainReportInputs, output_path: Path) -> Path:
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer
    except ModuleNotFoundError as exc:
        raise RuntimeError(
            "PDF generation requires the optional 'reportlab' package. "
            "Install it in the active environment or omit --output-pdf."
        ) from exc

    output_path.parent.mkdir(parents=True, exist_ok=True)

    markdown = generate_markdown_report(inputs)
    styles = getSampleStyleSheet()
    story = []
    for line in markdown_to_plain_lines(markdown):
        if not line:
            story.append(Spacer(1, 8))
            continue
        style = styles["Heading2"] if line.endswith(":") else styles["BodyText"]
        story.append(Paragraph(line, style))

    document = SimpleDocTemplate(str(output_path), pagesize=letter)
    document.build(story)
    return output_path
